language: none

branches:
  only:
    - master

build:
  ci:
    - git remote set-url origin git@github.com:justin8/docker-simple-proxy.git
    # Update armhf branch
    - git checkout armhf
    - git rebase origin/master
    - GIT_SSH_COMMAND="ssh -i /tmp/ssh/shippabledockersimpleproxydeploykey" git push -f

integrations:
  key:
    - integrationName: shippable-docker-simple-proxy-deploy-key
      type: ssh-key
